create or replace PACKAGE BODY  "APIINST"."PKG_API_CONS" AS
PROCEDURE PRC_GET_TAREAS(
X_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
OPEN X_CURSOR FOR
SELECT ID_TAREA,ID_TIPO_TAREA 
FROM TAREAS
WHERE ESTADO = 2;
END PRC_GET_TAREAS;


PROCEDURE PRC_GET_TAREA_EXPANCION(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
OPEN X_CURSOR FOR 
SELECT TA.ID_TAREA,MET.ID_METHODLIKE,MET.VELOCIDAD,MET.USUARIOS,ML.CANTLIKE,LOG.USUARIO,LOG.PASS
FROM TAREAS TA
INNER JOIN METHODLIKE MET ON MET.ID_TAREA = TA.ID_TAREA
INNER JOIN MLIKEMANYPOST ML ON ML.ID_MLIKE = MET.MLIKE
INNER JOIN MLOGIN LOG ON LOG.ID_MLOGIN = ML.ID_MLOGIN
WHERE 
MET.ID_TAREA = X_ID_TAREA AND TA.ESTADO = 2;
END PRC_GET_TAREA_EXPANCION;

--Procedimiento para obtener tarea de Purificacion
PROCEDURE PRC_GET_TAREA_PURIFICACION
(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
OPEN X_CURSOR FOR 
SELECT
TA.ID_TAREA,PUR.ID_PURIFICADOR,PUR.USUARIOS,LOG.USUARIO,LOG.PASS
FROM 
TAREAS TA
INNER JOIN PURIFICADOR PUR ON PUR.ID_TAREA = TA.ID_TAREA
INNER JOIN MLOGIN LOG ON LOG.ID_MLOGIN = PUR.ID_USUARIO
WHERE PUR.ID_TAREA = X_ID_TAREA;
END PRC_GET_TAREA_PURIFICACION;

--Obtener Reportes de los Mensajes Enviados a los usuarios
PROCEDURE PRC_GET_REPORES_MSJ(
X_CLIENTE_ID IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
OPEN X_CURSOR FOR 
SELECT RE.THREAD_ID,RE.ITEM_ID,RE.CLIENTE_ID,RE.CANT_TOTAL,RE.CANT_ENV,RE.CANT_VISTOS,RE.CANT_REACC,RE.LIST_IDS
FROM REPORT_MESS RE 
WHERE 
RE.CLIENTE_ID = X_CLIENTE_ID;
END PRC_GET_REPORES_MSJ;

--Obtener Tarea MassSending para enviar los mensajes a una lista de usuarios
PROCEDURE PRC_GET_MASS_SENDING(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
OPEN X_CURSOR FOR 
SELECT MAS.USUARIOS, MAS.TEXTO, ML.USUARIO, ML.PASS  
FROM MASSENDING MAS 
INNER JOIN TAREAS TA ON TA.ID_TAREA = MAS.IDTAREA
INNER JOIN MLOGIN ML ON ML.ID_MLOGIN = MAS.IDMLOGIN
WHERE 
TA.ID_TAREA = X_ID_TAREA AND TA.ESTADO = 2;

END PRC_GET_MASS_SENDING;
END PKG_API_CONS;

