--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-25-2020   
--------------------------------------------------------
DROP SEQUENCE "SYS_ERROR"."SE_ID_ERROR";
DROP TABLE "SYS_ERROR"."ERROR_SYS" cascade constraints;
DROP PACKAGE "SYS_ERROR"."PKG_MANT_ERROR";
DROP PACKAGE BODY "SYS_ERROR"."PKG_MANT_ERROR";
--------------------------------------------------------
--  DDL for Sequence SE_ID_ERROR
--------------------------------------------------------

   CREATE SEQUENCE  "SYS_ERROR"."SE_ID_ERROR"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ERROR_SYS
--------------------------------------------------------

  CREATE TABLE "SYS_ERROR"."ERROR_SYS" 
   (	"ID_TIPO" NUMBER, 
	"DESC_ERROR" VARCHAR2(300 BYTE), 
	"ACTION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_APIINST" ;

   COMMENT ON COLUMN "SYS_ERROR"."ERROR_SYS"."ID_TIPO" IS 'ID Y TIPO DE ERROR';
   COMMENT ON COLUMN "SYS_ERROR"."ERROR_SYS"."DESC_ERROR" IS 'DESCRIPCION DEL ERROR';
   COMMENT ON COLUMN "SYS_ERROR"."ERROR_SYS"."ACTION" IS 'ACCION A TOMAR SEGÚN EL TIPO DE ERROR 1-PARAR TAREA ESPECIFICA 2-PAAR TODAS LAS TAREAS DEL USUARIO 3-PARAR TODAS LAS TAREAS 4-PENDIENTE POR LA ADMINISTRACION';
REM INSERTING into SYS_ERROR.ERROR_SYS
SET DEFINE OFF;
Insert into SYS_ERROR.ERROR_SYS (ID_TIPO,DESC_ERROR,ACTION) values ('2','EJEMPLO1','4');
--------------------------------------------------------
--  DDL for Index ERROR_SYS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_ERROR"."ERROR_SYS_PK" ON "SYS_ERROR"."ERROR_SYS" ("ID_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_APIINST" ;
--------------------------------------------------------
--  DDL for Package PKG_MANT_ERROR
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SYS_ERROR"."PKG_MANT_ERROR" AS 

PROCEDURE PRC_SYS_ERROR(
X_DESC_ERROR IN SYS_ERROR.error_sys.DESC_ERROR%TYPE,
X_CURSOR OUT SYS_REFCURSOR
);

END PKG_MANT_ERROR;

/

  GRANT EXECUTE ON "SYS_ERROR"."PKG_MANT_ERROR" TO "APIINST";
--------------------------------------------------------
--  DDL for Package Body PKG_MANT_ERROR
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "SYS_ERROR"."PKG_MANT_ERROR" AS

  PROCEDURE PRC_SYS_ERROR(
X_DESC_ERROR IN SYS_ERROR.error_sys.DESC_ERROR%TYPE,
X_CURSOR OUT SYS_REFCURSOR
) IS
X_EXISTE NUMBER;
  BEGIN
 SELECT COUNT(ID_TIPO) INTO X_EXISTE FROM ERROR_SYS WHERE DESC_ERROR = X_DESC_ERROR;
 IF X_EXISTE = 0 THEN
 INSERT INTO ERROR_SYS
 (
 ID_TIPO,
 DESC_ERROR,
 ACTION
 )
 VALUES
 (
 SYS_ERROR.SE_ID_ERROR.NEXTVAL,
 X_DESC_ERROR,
 4
 );
 ELSE 
 OPEN X_CURSOR FOR 
 SELECT ID_TIPO,ACTION FROM ERROR_SYS WHERE DESC_ERROR = X_DESC_ERROR;
 END IF;
 END PRC_SYS_ERROR;

END PKG_MANT_ERROR;

/

  GRANT EXECUTE ON "SYS_ERROR"."PKG_MANT_ERROR" TO "APIINST";
--------------------------------------------------------
--  Constraints for Table ERROR_SYS
--------------------------------------------------------

  ALTER TABLE "SYS_ERROR"."ERROR_SYS" ADD CONSTRAINT "ERROR_SYS_PK" PRIMARY KEY ("ID_TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_APIINST"  ENABLE;
  ALTER TABLE "SYS_ERROR"."ERROR_SYS" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "SYS_ERROR"."ERROR_SYS" MODIFY ("DESC_ERROR" NOT NULL ENABLE);
  ALTER TABLE "SYS_ERROR"."ERROR_SYS" MODIFY ("ID_TIPO" NOT NULL ENABLE);
