--------------------------------------------------------
-- Archivo creado  - lunes-noviembre-23-2020   
--------------------------------------------------------
DROP TABLE "APIINST"."PURIFICADOR" cascade constraints;
DROP TABLE "APIINST"."MLOGIN" cascade constraints;
DROP TABLE "APIINST"."TAREAS" cascade constraints;
--------------------------------------------------------
--  DDL for Table PURIFICADOR
--------------------------------------------------------

  CREATE TABLE "APIINST"."PURIFICADOR" 
   (	"ID_PURIFICADOR" NUMBER, 
	"USUARIO" VARCHAR2(255 BYTE), 
	"USUARIOS" CLOB, 
	"ID_USUARIO" NUMBER, 
	"ID_TAREA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("USUARIOS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MLOGIN
--------------------------------------------------------

  CREATE TABLE "APIINST"."MLOGIN" 
   (	"ID_MLOGIN" NUMBER, 
	"USUARIO" VARCHAR2(255 BYTE), 
	"PASS" VARCHAR2(255 BYTE), 
	"PROXY" NUMBER, 
	"DEVICE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAREAS
--------------------------------------------------------

  CREATE TABLE "APIINST"."TAREAS" 
   (	"ID_TAREA" NUMBER, 
	"ID_TIPO_TAREA" NUMBER, 
	"ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "APIINST"."TAREAS"."ESTADO" IS '0-FALSE,1-TRUE,2-PENDING';
REM INSERTING into APIINST.PURIFICADOR
SET DEFINE OFF;
Insert into APIINST.PURIFICADOR (ID_PURIFICADOR,USUARIO,ID_USUARIO,ID_TAREA) values ('1','raulalex1995','1','44');
--------------------------------------------------------
--  DDL for Index PURIFICADOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."PURIFICADOR_PK" ON "APIINST"."PURIFICADOR" ("ID_PURIFICADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PURIFICADOR
--------------------------------------------------------

  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("ID_TAREA" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PURIFICADOR" ADD CONSTRAINT "PURIFICADOR_PK" PRIMARY KEY ("ID_PURIFICADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("USUARIOS" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("ID_PURIFICADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PURIFICADOR
--------------------------------------------------------

  ALTER TABLE "APIINST"."PURIFICADOR" ADD CONSTRAINT "ID_MLOGIN_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "APIINST"."MLOGIN" ("ID_MLOGIN") ON DELETE CASCADE ENABLE;
  ALTER TABLE "APIINST"."PURIFICADOR" ADD CONSTRAINT "ID_TAREA_PURI_FK" FOREIGN KEY ("ID_TAREA")
	  REFERENCES "APIINST"."TAREAS" ("ID_TAREA") ON DELETE CASCADE ENABLE;
