--------------------------------------------------------
-- Archivo creado  - miércoles-noviembre-25-2020   
--------------------------------------------------------
DROP SEQUENCE "APIINST"."SE_ID_ANDROIDVERSION";
DROP SEQUENCE "APIINST"."SE_IDMASENDING";
DROP SEQUENCE "APIINST"."SE_ID_METHOLIKE";
DROP SEQUENCE "APIINST"."SE_ID_MLIKE";
DROP SEQUENCE "APIINST"."SE_ID_PROXY";
DROP SEQUENCE "APIINST"."SE_ID_PURIFICADOR";
DROP SEQUENCE "APIINST"."SE_ID_TAREAS";
DROP SEQUENCE "APIINST"."SE_ID_USUARIO";
DROP TABLE "APIINST"."ANDROID_VERSION" cascade constraints;
DROP TABLE "APIINST"."BITACORA" cascade constraints;
DROP TABLE "APIINST"."DEVICE" cascade constraints;
DROP TABLE "APIINST"."MASSENDING" cascade constraints;
DROP TABLE "APIINST"."METHODLIKE" cascade constraints;
DROP TABLE "APIINST"."MFOLLOWER" cascade constraints;
DROP TABLE "APIINST"."MLIKEMANYPOST" cascade constraints;
DROP TABLE "APIINST"."MLOGIN" cascade constraints;
DROP TABLE "APIINST"."PROXY" cascade constraints;
DROP TABLE "APIINST"."PURIFICADOR" cascade constraints;
DROP TABLE "APIINST"."REPORTES" cascade constraints;
DROP TABLE "APIINST"."REPORT_MESS" cascade constraints;
DROP TABLE "APIINST"."TAREAS" cascade constraints;
DROP TABLE "APIINST"."TIPO_TAREA" cascade constraints;
DROP TABLE "APIINST"."USUARIOS" cascade constraints;
DROP PACKAGE "APIINST"."PKG_API_CONS";
DROP PACKAGE "APIINST"."PKG_API_MANT";
DROP PACKAGE BODY "APIINST"."PKG_API_CONS";
DROP PACKAGE BODY "APIINST"."PKG_API_MANT";
--------------------------------------------------------
--  DDL for Sequence SE_ID_ANDROIDVERSION
--------------------------------------------------------

   CREATE SEQUENCE  "APIINST"."SE_ID_ANDROIDVERSION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_IDMASENDING
--------------------------------------------------------

   CREATE SEQUENCE  "APIINST"."SE_IDMASENDING"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_ID_METHOLIKE
--------------------------------------------------------

   CREATE SEQUENCE  "APIINST"."SE_ID_METHOLIKE"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 24 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_ID_MLIKE
--------------------------------------------------------

   CREATE SEQUENCE  "APIINST"."SE_ID_MLIKE"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 24 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_ID_PROXY
--------------------------------------------------------

   CREATE SEQUENCE  "APIINST"."SE_ID_PROXY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_ID_PURIFICADOR
--------------------------------------------------------

   CREATE SEQUENCE  "APIINST"."SE_ID_PURIFICADOR"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_ID_TAREAS
--------------------------------------------------------

   CREATE SEQUENCE  "APIINST"."SE_ID_TAREAS"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 45 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SE_ID_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "APIINST"."SE_ID_USUARIO"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ANDROID_VERSION
--------------------------------------------------------

  CREATE TABLE "APIINST"."ANDROID_VERSION" 
   (	"CODENAME" VARCHAR2(20 BYTE), 
	"VERSIONNUMBER" VARCHAR2(20 BYTE), 
	"APILEVEL" VARCHAR2(20 BYTE), 
	"IDANDROIDVERSION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BITACORA
--------------------------------------------------------

  CREATE TABLE "APIINST"."BITACORA" 
   (	"ID_LOG" NUMBER, 
	"PK_LOGIN" VARCHAR2(255 BYTE), 
	"ID_TAREA" NUMBER, 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"FECHA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEVICE
--------------------------------------------------------

  CREATE TABLE "APIINST"."DEVICE" 
   (	"ADID" VARCHAR2(255 BYTE), 
	"ANDROIDBOARDNAME" VARCHAR2(255 BYTE), 
	"ANDROIDBOOTLOADER" VARCHAR2(255 BYTE), 
	"ANDROIDVER" NUMBER, 
	"DEVICEBRAND" VARCHAR2(255 BYTE), 
	"DEVICEGUID" VARCHAR2(255 BYTE), 
	"DEVICEID" VARCHAR2(255 BYTE), 
	"DEVICEMODEL" VARCHAR2(255 BYTE), 
	"DEVICEMODELBOOT" VARCHAR2(255 BYTE), 
	"DEVICEMODELIDENTIFIER" VARCHAR2(255 BYTE), 
	"DPI" VARCHAR2(255 BYTE), 
	"RESOLUTION" VARCHAR2(255 BYTE), 
	"FIRMWAREFINGERPRINT" VARCHAR2(255 BYTE), 
	"FIRMWARETAGS" VARCHAR2(255 BYTE), 
	"FIRMWARETYPE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "APIINST"."DEVICE"."ADID" IS 'ID_DISPOSITIVO';
   COMMENT ON COLUMN "APIINST"."DEVICE"."ANDROIDVER" IS 'ID ANDROID VERSION';
--------------------------------------------------------
--  DDL for Table MASSENDING
--------------------------------------------------------

  CREATE TABLE "APIINST"."MASSENDING" 
   (	"IDMASSENDING" NUMBER, 
	"PK_MLOGIN" VARCHAR2(255 BYTE), 
	"USUARIOS" VARCHAR2(4000 BYTE), 
	"TEXTO" VARCHAR2(4000 BYTE), 
	"IDTAREA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table METHODLIKE
--------------------------------------------------------

  CREATE TABLE "APIINST"."METHODLIKE" 
   (	"ID_METHODLIKE" NUMBER, 
	"VELOCIDAD" NUMBER, 
	"MLIKE" NUMBER, 
	"ID_TAREA" NUMBER, 
	"USUARIOS" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("USUARIOS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MFOLLOWER
--------------------------------------------------------

  CREATE TABLE "APIINST"."MFOLLOWER" 
   (	"PK_OTHERUSER" NUMBER, 
	"OTHERUSER" VARCHAR2(255 BYTE), 
	"PK_MLOGIN" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MLIKEMANYPOST
--------------------------------------------------------

  CREATE TABLE "APIINST"."MLIKEMANYPOST" 
   (	"ID_MLIKE" NUMBER, 
	"USERLIKE" VARCHAR2(255 BYTE), 
	"USERFOLLOW" VARCHAR2(20 BYTE), 
	"CANTLIKE" NUMBER, 
	"TIME" VARCHAR2(20 BYTE), 
	"PK_MLOGIN" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MLOGIN
--------------------------------------------------------

  CREATE TABLE "APIINST"."MLOGIN" 
   (	"USUARIO" VARCHAR2(255 BYTE), 
	"PASS" VARCHAR2(255 BYTE), 
	"PROXY" NUMBER, 
	"DEVICE" VARCHAR2(20 BYTE), 
	"PK" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROXY
--------------------------------------------------------

  CREATE TABLE "APIINST"."PROXY" 
   (	"ID_PROXY" NUMBER, 
	"ADDRESSPROXY" VARCHAR2(255 BYTE), 
	"USERPROXY" VARCHAR2(255 BYTE), 
	"PASSPROXY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PURIFICADOR
--------------------------------------------------------

  CREATE TABLE "APIINST"."PURIFICADOR" 
   (	"ID_PURIFICADOR" NUMBER, 
	"USUARIO" VARCHAR2(255 BYTE), 
	"USUARIOS" CLOB, 
	"PK_MLOGIN" VARCHAR2(255 BYTE), 
	"ID_TAREA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("USUARIOS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table REPORTES
--------------------------------------------------------

  CREATE TABLE "APIINST"."REPORTES" 
   (	"ID_REPORTE" NUMBER, 
	"DESCRIPCION" CLOB, 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPCION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table REPORT_MESS
--------------------------------------------------------

  CREATE TABLE "APIINST"."REPORT_MESS" 
   (	"THREAD_ID" VARCHAR2(4000 BYTE), 
	"ITEM_ID" VARCHAR2(4000 BYTE), 
	"PK_MLOGIN" VARCHAR2(255 BYTE), 
	"CANT_TOTAL" NUMBER, 
	"CANT_ENV" NUMBER, 
	"CANT_VISTOS" NUMBER, 
	"CANT_REACC" NUMBER, 
	"LIST_IDS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAREAS
--------------------------------------------------------

  CREATE TABLE "APIINST"."TAREAS" 
   (	"ID_TAREA" NUMBER, 
	"ID_TIPO_TAREA" NUMBER, 
	"ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "APIINST"."TAREAS"."ESTADO" IS '0-FALSE,1-TRUE,2-PENDING';
--------------------------------------------------------
--  DDL for Table TIPO_TAREA
--------------------------------------------------------

  CREATE TABLE "APIINST"."TIPO_TAREA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "APIINST"."TIPO_TAREA"."ID" IS 'IDENTIFICADOR DE TAREAS';
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "APIINST"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"USERNAME" VARCHAR2(255 BYTE), 
	"METHODLIKE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APIINST.ANDROID_VERSION
SET DEFINE OFF;
Insert into APIINST.ANDROID_VERSION (CODENAME,VERSIONNUMBER,APILEVEL,IDANDROIDVERSION) values ('1','1','1','1');
REM INSERTING into APIINST.BITACORA
SET DEFINE OFF;
REM INSERTING into APIINST.DEVICE
SET DEFINE OFF;
Insert into APIINST.DEVICE (ADID,ANDROIDBOARDNAME,ANDROIDBOOTLOADER,ANDROIDVER,DEVICEBRAND,DEVICEGUID,DEVICEID,DEVICEMODEL,DEVICEMODELBOOT,DEVICEMODELIDENTIFIER,DPI,RESOLUTION,FIRMWAREFINGERPRINT,FIRMWARETAGS,FIRMWARETYPE) values ('1','1','1','1','1','1','1','1','1','1','1','1','1','1','1');
REM INSERTING into APIINST.MASSENDING
SET DEFINE OFF;
REM INSERTING into APIINST.METHODLIKE
SET DEFINE OFF;
REM INSERTING into APIINST.MFOLLOWER
SET DEFINE OFF;
REM INSERTING into APIINST.MLIKEMANYPOST
SET DEFINE OFF;
REM INSERTING into APIINST.MLOGIN
SET DEFINE OFF;
REM INSERTING into APIINST.PROXY
SET DEFINE OFF;
Insert into APIINST.PROXY (ID_PROXY,ADDRESSPROXY,USERPROXY,PASSPROXY) values ('1','1','1','1');
REM INSERTING into APIINST.PURIFICADOR
SET DEFINE OFF;
REM INSERTING into APIINST.REPORTES
SET DEFINE OFF;
REM INSERTING into APIINST.REPORT_MESS
SET DEFINE OFF;
REM INSERTING into APIINST.TAREAS
SET DEFINE OFF;
Insert into APIINST.TAREAS (ID_TAREA,ID_TIPO_TAREA,ESTADO) values ('39','1','2');
Insert into APIINST.TAREAS (ID_TAREA,ID_TIPO_TAREA,ESTADO) values ('43','1','2');
Insert into APIINST.TAREAS (ID_TAREA,ID_TIPO_TAREA,ESTADO) values ('44','2','2');
REM INSERTING into APIINST.TIPO_TAREA
SET DEFINE OFF;
Insert into APIINST.TIPO_TAREA (ID,NOMBRE) values ('1','METHODLIKE');
Insert into APIINST.TIPO_TAREA (ID,NOMBRE) values ('2','ACTIVO INACTIVO');
REM INSERTING into APIINST.USUARIOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ANDROID_VERSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."ANDROID_VERSION_PK" ON "APIINST"."ANDROID_VERSION" ("IDANDROIDVERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROXY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."PROXY_PK" ON "APIINST"."PROXY" ("ID_PROXY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MASSENDING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."MASSENDING_PK" ON "APIINST"."MASSENDING" ("IDMASSENDING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BITACORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."BITACORA_PK" ON "APIINST"."BITACORA" ("ID_LOG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAREAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."TAREAS_PK" ON "APIINST"."TAREAS" ("ID_TAREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PURIFICADOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."PURIFICADOR_PK" ON "APIINST"."PURIFICADOR" ("ID_PURIFICADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."USUARIOS_PK" ON "APIINST"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index METHODLIKE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."METHODLIKE_PK" ON "APIINST"."METHODLIKE" ("ID_METHODLIKE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MLOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."MLOGIN_PK" ON "APIINST"."MLOGIN" ("PK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_APIINST" ;
--------------------------------------------------------
--  DDL for Index REPORTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."REPORTES_PK" ON "APIINST"."REPORTES" ("ID_REPORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."DEVICE_PK" ON "APIINST"."DEVICE" ("DEVICEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MLIKEMANYPOST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."MLIKEMANYPOST_PK" ON "APIINST"."MLIKEMANYPOST" ("ID_MLIKE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MFOLLOWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."MFOLLOWER_PK" ON "APIINST"."MFOLLOWER" ("PK_OTHERUSER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPORT_MESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."REPORT_MESS_PK" ON "APIINST"."REPORT_MESS" ("THREAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_APIINST" ;
--------------------------------------------------------
--  DDL for Index TIPO_TAREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APIINST"."TIPO_TAREA_PK" ON "APIINST"."TIPO_TAREA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Package PKG_API_CONS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "APIINST"."PKG_API_CONS" AS 

PROCEDURE PRC_GET_TAREAS(
X_CURSOR OUT SYS_REFCURSOR);
--Procedimiento para obtener tarea Expancion
PROCEDURE PRC_GET_TAREA_EXPANCION(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR);

--Procedimiento para obtener tarea de Purificacion
PROCEDURE PRC_GET_TAREA_PURIFICACION
(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR
);

PROCEDURE PRC_GET_REPORES_MSJ(
X_CLIENTE_ID IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR);
PROCEDURE PRC_GET_MASS_SENDING(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR);

END PKG_API_CONS;

/
--------------------------------------------------------
--  DDL for Package PKG_API_MANT
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "APIINST"."PKG_API_MANT" AS 
PROCEDURE PRC_TAREA_INSERTAR (
X_ID_TIPO IN apiinst.tareas.ID_TIPO_TAREA%TYPE,
X_USER IN apiinst.mlogin.USUARIO%TYPE,
X_VEL IN apiinst.methodlike.VELOCIDAD%TYPE,
X_CANT IN apiinst.mlikemanypost.CANTLIKE%TYPE,
X_USERLIST IN apiinst.methodlike.USUARIOS%TYPE,
X_ERROR OUT SYS_REFCURSOR
);

--Procedimiento para Insetar Valores en la Tabla Reportes_Mensajes(REPORT_MESS)
PROCEDURE PRC_INSERT_REPORT_MESS (
X_THREAD_ID IN apiinst.report_mess.THREAD_ID%TYPE,
X_ITEM_ID IN apiinst.report_mess.ITEM_ID%TYPE,
X_CLIENTE_ID IN apiinst.report_mess.PK_MLOGIN%TYPE,
X_CANT_TOTAL IN apiinst.report_mess.CANT_TOTAL%TYPE,
X_CANT_ENV IN apiinst.report_mess.CANT_ENV%TYPE,
X_LIST_IDS IN apiinst.report_mess.LIST_IDS%TYPE,
X_ERROR OUT SYS_REFCURSOR
);


--Procedimiento par actualizar la tabla de los reportes de mensajes
PROCEDURE PRC_UPDATE_REPORT_MESS (
X_THREAD_ID IN apiinst.report_mess.THREAD_ID%TYPE,
X_CLIENTE_ID IN apiinst.report_mess.PK_MLOGIN%TYPE,
X_CANT_VISTOS IN apiinst.report_mess.CANT_VISTOS%TYPE,
X_CANT_REACC IN apiinst.report_mess.CANT_REACC%TYPE,
X_ERROR OUT SYS_REFCURSOR
);

--Procedimiento para insertar la tarea de purificar cuentas
PROCEDURE PRC_PURIFICADOR_INSERTAR
(X_USUARIO IN apiinst.purificador.USUARIO%TYPE,
X_USUARIOS IN apiinst.purificador.USUARIOS%TYPE,
X_ID_TIPO IN apiinst.tareas.ID_TIPO_TAREA%TYPE,
X_ERROR OUT SYS_REFCURSOR
);

PROCEDURE PRC_MASSENDING_INSERTAR(
X_USUARIO IN apiinst.MLOGIN.USUARIO%TYPE,
X_USUARIOS IN apiinst.massending.USUARIOS%TYPE,
X_TEXTO IN apiinst.massending.TEXTO%TYPE,
X_ID_TIPO IN apiinst.tareas.ID_TIPO_TAREA%TYPE,
X_ERROR OUT SYS_REFCURSOR
);

--Proceso Mlogin--Aqui Se insertan los device, proxy, login--
PROCEDURE PRC_MLOGIN_INSERTAR(
X_CODENAME IN APIINST.ANDROID_VERSION.CODENAME%TYPE,
X_VERSIONUMBER IN APIINST.ANDROID_VERSION.VERSIONNUMBER%TYPE,
X_APILEVEL IN APIINST.ANDROID_VERSION.APILEVEL%TYPE,
X_ADID IN APIINST.DEVICE.ADID%TYPE,
X_ANDBOARDNAME IN APIINST.DEVICE.ANDROIDBOARDNAME%TYPE,
X_ANDBOOTLOADER IN APIINST.DEVICE.ANDROIDBOOTLOADER%TYPE,
X_DEVICEBRAND IN APIINST.DEVICE.DEVICEBRAND%TYPE,
X_DEVICEGUID IN APIINST.DEVICE.DEVICEGUID%TYPE,
X_DEVICEID IN APIINST.DEVICE.DEVICEID%TYPE,
X_DEVICEMODEL IN APIINST.DEVICE.DEVICEMODEL%TYPE,
X_DEVICEMODELBOOT IN APIINST.DEVICE.DEVICEMODELBOOT%TYPE,
X_DEVICEMODELIDENTIFIER IN APIINST.DEVICE.DEVICEMODELIDENTIFIER%TYPE,
X_DPI IN APIINST.DEVICE.DPI%TYPE,
X_RESOLUTION IN APIINST.DEVICE.RESOLUTION%TYPE,
X_FIRMWAREFINGERPRINT IN APIINST.DEVICE.FIRMWAREFINGERPRINT%TYPE,
X_FIRMWARETAGS IN APIINST.DEVICE.FIRMWARETAGS%TYPE,
X_FIRMWARETYPE IN APIINST.DEVICE.FIRMWARETYPE%TYPE,
X_ADDRESSPROXY IN APIINST.PROXY.ADDRESSPROXY%TYPE,
X_USERPROXY IN APIINST.PROXY.USERPROXY%TYPE,
X_PASSPROXY IN APIINST.PROXY.PASSPROXY%TYPE,
X_USUARIO IN APIINST.MLOGIN.USUARIO%TYPE,
X_PASS IN APIINST.MLOGIN.PASS%TYPE,
X_PK IN APIINST.MLOGIN.PK%TYPE,
X_ERROR OUT SYS_REFCURSOR
);


END PKG_API_MANT;

/
--------------------------------------------------------
--  DDL for Package Body PKG_API_CONS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "APIINST"."PKG_API_CONS" AS
PROCEDURE PRC_GET_TAREAS(
X_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
OPEN X_CURSOR FOR
SELECT ID_TAREA,ID_TIPO_TAREA 
FROM TAREAS
WHERE ESTADO = 2;
END PRC_GET_TAREAS;


PROCEDURE PRC_GET_TAREA_EXPANCION(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
OPEN X_CURSOR FOR 
SELECT TA.ID_TAREA,MET.ID_METHODLIKE,MET.VELOCIDAD,MET.USUARIOS,ML.CANTLIKE,LOG.USUARIO,LOG.PASS
FROM TAREAS TA
INNER JOIN METHODLIKE MET ON MET.ID_TAREA = TA.ID_TAREA
INNER JOIN MLIKEMANYPOST ML ON ML.ID_MLIKE = MET.MLIKE
INNER JOIN MLOGIN LOG ON LOG.PK = ML.PK_MLOGIN
WHERE 
MET.ID_TAREA = X_ID_TAREA AND TA.ESTADO = 2;
END PRC_GET_TAREA_EXPANCION;

--Procedimiento para obtener tarea de Purificacion
PROCEDURE PRC_GET_TAREA_PURIFICACION
(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
OPEN X_CURSOR FOR 
SELECT
TA.ID_TAREA,PUR.ID_PURIFICADOR,PUR.USUARIOS,LOG.USUARIO,LOG.PASS
FROM 
TAREAS TA
INNER JOIN PURIFICADOR PUR ON PUR.ID_TAREA = TA.ID_TAREA
INNER JOIN MLOGIN LOG ON LOG.PK = PUR.PK_MLOGIN
WHERE PUR.ID_TAREA = X_ID_TAREA;
END PRC_GET_TAREA_PURIFICACION;

--Obtener Reportes de los Mensajes Enviados a los usuarios
PROCEDURE PRC_GET_REPORES_MSJ(
X_CLIENTE_ID IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
OPEN X_CURSOR FOR 
SELECT RE.THREAD_ID,RE.ITEM_ID,RE.PK_MLOGIN,RE.CANT_TOTAL,RE.CANT_ENV,RE.CANT_VISTOS,RE.CANT_REACC,RE.LIST_IDS
FROM REPORT_MESS RE 
WHERE 
RE.PK_MLOGIN = X_CLIENTE_ID;
END PRC_GET_REPORES_MSJ;

--Obtener Tarea MassSending para enviar los mensajes a una lista de usuarios
PROCEDURE PRC_GET_MASS_SENDING(
X_ID_TAREA IN NUMBER,
X_CURSOR OUT SYS_REFCURSOR)
IS
BEGIN
OPEN X_CURSOR FOR 
SELECT MAS.USUARIOS, MAS.TEXTO, ML.USUARIO, ML.PASS  
FROM MASSENDING MAS 
INNER JOIN TAREAS TA ON TA.ID_TAREA = MAS.IDTAREA
INNER JOIN MLOGIN ML ON ML.PK = MAS.PK_MLOGIN
WHERE 
TA.ID_TAREA = X_ID_TAREA AND TA.ESTADO = 2;

END PRC_GET_MASS_SENDING;
END PKG_API_CONS;

/
--------------------------------------------------------
--  DDL for Package Body PKG_API_MANT
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "APIINST"."PKG_API_MANT" AS
PROCEDURE PRC_TAREA_INSERTAR (
X_ID_TIPO IN apiinst.tareas.ID_TIPO_TAREA%TYPE,
X_USER IN apiinst.mlogin.USUARIO%TYPE,
X_VEL IN apiinst.methodlike.VELOCIDAD%TYPE,
X_CANT IN apiinst.mlikemanypost.CANTLIKE%TYPE,
X_USERLIST IN apiinst.methodlike.USUARIOS%TYPE,
X_ERROR OUT SYS_REFCURSOR
)
IS
X_ID_TAREA NUMBER;
X_ID_METHODLIKE NUMBER;
X_ID_MLIKE NUMBER;
X_ERROR_DESC VARCHAR2(300);
BEGIN
BEGIN
X_ID_TAREA := SE_ID_TAREAS.NEXTVAL;
X_ID_METHODLIKE := SE_ID_METHOLIKE.nextval;
X_ID_MLIKE := SE_ID_MLIKE.nextval;
INSERT INTO TAREAS
(
ID_TAREA,
ID_TIPO_TAREA,
ESTADO
)
VALUES 
(
X_ID_TAREA,
X_ID_TIPO,
2
);
INSERT INTO mlikemanypost
(
id_mlike,
cantlike,
pk_mlogin
)
VALUES 
(
X_ID_MLIKE,
X_CANT,
(SELECT PK FROM MLOGIN WHERE USUARIO = X_USER)
);
INSERT INTO methodlike
(
ID_METHODLIKE,
VELOCIDAD,
MLIKE,
ID_TAREA,
USUARIOS
)
VALUES 
(
X_ID_METHODLIKE,
X_VEL,
X_ID_MLIKE,
X_ID_TAREA,
X_USERLIST
);

OPEN X_ERROR FOR
        SELECT TO_CHAR(X_ID_TAREA) AS "VALOR", 0 AS "ID_TIPO", '0' AS "ID_ERROR", '' AS "DES_ERROR"
        FROM DUAL;
EXCEPTION WHEN OTHERS THEN

OPEN X_ERROR FOR
      SELECT X_ERROR_DESC AS "VALOR", 1 AS "ID_TIPO", '1' AS "ID_ERROR", 'OCURRIO UN ERROR NO CONTROLADO' AS "DES_ERROR", '' AS "VALOR1"
      FROM DUAL;
END;
END PRC_TAREA_INSERTAR;

--Procedimiento para Insetar Valores en la Tabla Reportes_Mensajes(REPORT_MESS)
PROCEDURE PRC_INSERT_REPORT_MESS (
X_THREAD_ID IN apiinst.report_mess.THREAD_ID%TYPE,
X_ITEM_ID IN apiinst.report_mess.ITEM_ID%TYPE,
X_CLIENTE_ID IN apiinst.report_mess.PK_MLOGIN%TYPE,
X_CANT_TOTAL IN apiinst.report_mess.CANT_TOTAL%TYPE,
X_CANT_ENV IN apiinst.report_mess.CANT_ENV%TYPE,
X_LIST_IDS IN apiinst.report_mess.LIST_IDS%TYPE,
X_ERROR OUT SYS_REFCURSOR
)
IS
X_ERROR_DESC VARCHAR2(300);

BEGIN
BEGIN
INSERT INTO REPORT_MESS
(
THREAD_ID,
ITEM_ID,
PK_MLOGIN,
CANT_TOTAL,
CANT_ENV,
LIST_IDS
)
VALUES 
(
X_THREAD_ID,
X_ITEM_ID,
X_CLIENTE_ID,
X_CANT_TOTAL,
X_CANT_ENV,
X_LIST_IDS
);

OPEN X_ERROR FOR
        SELECT TO_CHAR(X_THREAD_ID) AS "VALOR", 0 AS "ID_TIPO", '0' AS "ID_ERROR", '' AS "DES_ERROR"
        FROM DUAL;
EXCEPTION WHEN OTHERS THEN

OPEN X_ERROR FOR
      SELECT X_ERROR_DESC AS "VALOR", 1 AS "ID_TIPO", '1' AS "ID_ERROR", 'OCURRIO UN ERROR NO CONTROLADO' AS "DES_ERROR", '' AS "VALOR1"
      FROM DUAL;
END;

END PRC_INSERT_REPORT_MESS;



--Procedimiento para Actualizar los Valores en la Tabla Reportes_Mensajes(REPORT_MESS)
PROCEDURE PRC_UPDATE_REPORT_MESS (
X_THREAD_ID IN apiinst.report_mess.THREAD_ID%TYPE,
X_CLIENTE_ID IN apiinst.report_mess.PK_MLOGIN%TYPE,
X_CANT_VISTOS IN apiinst.report_mess.CANT_VISTOS%TYPE,
X_CANT_REACC IN apiinst.report_mess.CANT_REACC%TYPE,
X_ERROR OUT SYS_REFCURSOR
)
IS
X_ERROR_DESC VARCHAR2(300);

BEGIN
BEGIN
UPDATE REPORT_MESS
SET 
CANT_VISTOS = X_CANT_VISTOS,
CANT_REACC = X_CANT_REACC
WHERE THREAD_ID = X_THREAD_ID AND PK_MLOGIN = X_CLIENTE_ID;

OPEN X_ERROR FOR
        SELECT TO_CHAR(X_THREAD_ID) AS "VALOR", 0 AS "ID_TIPO", '0' AS "ID_ERROR", '' AS "DES_ERROR"
        FROM DUAL;
EXCEPTION WHEN OTHERS THEN

OPEN X_ERROR FOR
      SELECT X_ERROR_DESC AS "VALOR", 1 AS "ID_TIPO", '1' AS "ID_ERROR", 'OCURRIO UN ERROR NO CONTROLADO' AS "DES_ERROR", '' AS "VALOR1"
      FROM DUAL;
END;

END PRC_UPDATE_REPORT_MESS;

--Procedimiento para insertar la tarea de purificar cuentas
PROCEDURE PRC_PURIFICADOR_INSERTAR
(X_USUARIO IN apiinst.purificador.USUARIO%TYPE,
X_USUARIOS IN apiinst.purificador.USUARIOS%TYPE,
X_ID_TIPO IN apiinst.tareas.ID_TIPO_TAREA%TYPE,
X_ERROR OUT SYS_REFCURSOR
)
IS
X_ID_TAREA NUMBER;
X_ID_PURIFICADOR NUMBER;
X_ERROR_DESC VARCHAR2(300);
BEGIN
BEGIN
X_ID_TAREA := SE_ID_TAREAS.NEXTVAL;
X_ID_PURIFICADOR := APIINST.SE_ID_PURIFICADOR.NEXTVAL;
INSERT INTO TAREAS
(
ID_TAREA,
ID_TIPO_TAREA,
ESTADO
)
VALUES 
(
X_ID_TAREA,
X_ID_TIPO,
2
);
INSERT INTO PURIFICADOR
(
ID_PURIFICADOR,
USUARIO,
USUARIOS,
PK_MLOGIN,
ID_TAREA
)VALUES
(
X_ID_PURIFICADOR,
X_USUARIO,
X_USUARIOS,
(SELECT PK FROM MLOGIN WHERE USUARIO = X_USUARIO),
X_ID_TAREA
);
OPEN X_ERROR FOR
SELECT TO_CHAR(X_ID_PURIFICADOR) AS "VALOR", 0 AS "ID_TIPO", '0' AS "ID_ERROR", '' AS "DES_ERROR"
        FROM DUAL;
EXCEPTION WHEN OTHERS THEN

OPEN X_ERROR FOR
      SELECT X_ERROR_DESC AS "VALOR", 1 AS "ID_TIPO", '1' AS "ID_ERROR", 'OCURRIO UN ERROR NO CONTROLADO' AS "DES_ERROR", '' AS "VALOR1"
      FROM DUAL;
      END;
      END PRC_PURIFICADOR_INSERTAR;

PROCEDURE PRC_MASSENDING_INSERTAR(
X_USUARIO IN apiinst.MLOGIN.USUARIO%TYPE,
X_USUARIOS IN apiinst.massending.USUARIOS%TYPE,
X_TEXTO IN apiinst.massending.TEXTO%TYPE,
X_ID_TIPO IN apiinst.tareas.ID_TIPO_TAREA%TYPE,
X_ERROR OUT SYS_REFCURSOR
)
IS
X_ID_TAREA NUMBER;
X_IDMASSENDING NUMBER;
X_ERROR_DESC VARCHAR2(300);
BEGIN
BEGIN
X_ID_TAREA := APIINST.SE_ID_TAREAS.NEXTVAL;
X_IDMASSENDING := APIINST.SE_IDMASENDING.NEXTVAL;
INSERT INTO TAREAS
(
ID_TAREA,
ID_TIPO_TAREA,
ESTADO
)
VALUES 
(
X_ID_TAREA,
X_ID_TIPO,
2
);
INSERT INTO MASSENDING
(
IDMASSENDING,
PK_MLOGIN,
USUARIOS,
TEXTO,
IDTAREA
)
VALUES(
X_IDMASSENDING,
(SELECT PK FROM MLOGIN WHERE USUARIO = X_USUARIO),
X_USUARIOS,
X_TEXTO,
X_ID_TAREA
);

OPEN X_ERROR FOR
        SELECT TO_CHAR(X_IDMASSENDING) AS "VALOR", 0 AS "ID_TIPO", '0' AS "ID_ERROR", '' AS "DES_ERROR"
        FROM DUAL;
EXCEPTION WHEN OTHERS THEN

OPEN X_ERROR FOR
      SELECT X_ERROR_DESC AS "VALOR", 1 AS "ID_TIPO", '1' AS "ID_ERROR", 'OCURRIO UN ERROR NO CONTROLADO' AS "DES_ERROR", '' AS "VALOR1"
      FROM DUAL;
END;

END PRC_MASSENDING_INSERTAR;

--Proceso Mlogin--Aqui Se insertan los device, proxy, login--
PROCEDURE PRC_MLOGIN_INSERTAR(
X_CODENAME IN APIINST.ANDROID_VERSION.CODENAME%TYPE,
X_VERSIONUMBER IN APIINST.ANDROID_VERSION.VERSIONNUMBER%TYPE,
X_APILEVEL IN APIINST.ANDROID_VERSION.APILEVEL%TYPE,
X_ADID IN APIINST.DEVICE.ADID%TYPE,
X_ANDBOARDNAME IN APIINST.DEVICE.ANDROIDBOARDNAME%TYPE,
X_ANDBOOTLOADER IN APIINST.DEVICE.ANDROIDBOOTLOADER%TYPE,
X_DEVICEBRAND IN APIINST.DEVICE.DEVICEBRAND%TYPE,
X_DEVICEGUID IN APIINST.DEVICE.DEVICEGUID%TYPE,
X_DEVICEID IN APIINST.DEVICE.DEVICEID%TYPE,
X_DEVICEMODEL IN APIINST.DEVICE.DEVICEMODEL%TYPE,
X_DEVICEMODELBOOT IN APIINST.DEVICE.DEVICEMODELBOOT%TYPE,
X_DEVICEMODELIDENTIFIER IN APIINST.DEVICE.DEVICEMODELIDENTIFIER%TYPE,
X_DPI IN APIINST.DEVICE.DPI%TYPE,
X_RESOLUTION IN APIINST.DEVICE.RESOLUTION%TYPE,
X_FIRMWAREFINGERPRINT IN APIINST.DEVICE.FIRMWAREFINGERPRINT%TYPE,
X_FIRMWARETAGS IN APIINST.DEVICE.FIRMWARETAGS%TYPE,
X_FIRMWARETYPE IN APIINST.DEVICE.FIRMWARETYPE%TYPE,
X_ADDRESSPROXY IN APIINST.PROXY.ADDRESSPROXY%TYPE,
X_USERPROXY IN APIINST.PROXY.USERPROXY%TYPE,
X_PASSPROXY IN APIINST.PROXY.PASSPROXY%TYPE,
X_USUARIO IN APIINST.MLOGIN.USUARIO%TYPE,
X_PASS IN APIINST.MLOGIN.PASS%TYPE,
X_PK IN APIINST.MLOGIN.PK%TYPE,
X_ERROR OUT SYS_REFCURSOR
)
IS
X_IDANDROIDVERSION NUMBER;
X_ID_PROXY NUMBER;
X_ID_MLOGIN NUMBER;
X_ERROR_DESC VARCHAR2(300);

BEGIN
BEGIN
X_IDANDROIDVERSION := APIINST.SE_ID_ANDROIDVERSION.NEXTVAL;
X_ID_PROXY := APIINST.SE_ID_PROXY.NEXTVAL;

INSERT INTO ANDROID_VERSION
(
CODENAME,
VERSIONNUMBER,
APILEVEL,
IDANDROIDVERSION
)
VALUES 
(
X_CODENAME,
X_VERSIONUMBER,
X_APILEVEL,
X_IDANDROIDVERSION
);

INSERT INTO DEVICE
(
ADID,
ANDROIDBOARDNAME,
ANDROIDBOOTLOADER,
ANDROIDVER,
DEVICEBRAND,
DEVICEGUID,
DEVICEID,
DEVICEMODEL,
DEVICEMODELBOOT,
DEVICEMODELIDENTIFIER,
DPI,
RESOLUTION,
FIRMWAREFINGERPRINT,
FIRMWARETAGS,
FIRMWARETYPE
)
VALUES 
(
X_ADID,
X_ANDBOARDNAME,
X_ANDBOOTLOADER,
X_IDANDROIDVERSION,
X_DEVICEBRAND,
X_DEVICEGUID,
X_DEVICEID,
X_DEVICEMODEL,
X_DEVICEMODELBOOT,
X_DEVICEMODELIDENTIFIER,
X_DPI,
X_RESOLUTION,
X_FIRMWAREFINGERPRINT,
X_FIRMWARETAGS,
X_FIRMWARETYPE
);

INSERT INTO PROXY
(
ID_PROXY,
ADDRESSPROXY,
USERPROXY,
PASSPROXY
)
VALUES 
(
X_ID_PROXY,
X_ADDRESSPROXY,
X_USERPROXY,
X_PASSPROXY
);

INSERT INTO MLOGIN
(
USUARIO,
PASS,
PROXY,
DEVICE,
PK
)
VALUES 
(
X_USUARIO,
X_PASS,
X_ID_PROXY,
X_DEVICEID,
X_PK
);

OPEN X_ERROR FOR
        SELECT TO_CHAR(X_PK) AS "VALOR", 0 AS "ID_TIPO", '0' AS "ID_ERROR", '' AS "DES_ERROR"
        FROM DUAL;
EXCEPTION WHEN OTHERS THEN

OPEN X_ERROR FOR
      SELECT X_ERROR_DESC AS "VALOR", 1 AS "ID_TIPO", '1' AS "ID_ERROR", 'OCURRIO UN ERROR NO CONTROLADO' AS "DES_ERROR", '' AS "VALOR1"
      FROM DUAL;
END;

END PRC_MLOGIN_INSERTAR;



END PKG_API_MANT;

/
--------------------------------------------------------
--  Constraints for Table PROXY
--------------------------------------------------------

  ALTER TABLE "APIINST"."PROXY" ADD CONSTRAINT "PROXY_PK" PRIMARY KEY ("ID_PROXY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."PROXY" MODIFY ("PASSPROXY" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PROXY" MODIFY ("USERPROXY" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PROXY" MODIFY ("ADDRESSPROXY" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PROXY" MODIFY ("ID_PROXY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "APIINST"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."USUARIOS" MODIFY ("METHODLIKE" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."USUARIOS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORT_MESS
--------------------------------------------------------

  ALTER TABLE "APIINST"."REPORT_MESS" ADD CONSTRAINT "REPORT_MESS_PK" PRIMARY KEY ("THREAD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_APIINST"  ENABLE;
  ALTER TABLE "APIINST"."REPORT_MESS" MODIFY ("THREAD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAREAS
--------------------------------------------------------

  ALTER TABLE "APIINST"."TAREAS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."TAREAS" ADD CONSTRAINT "TAREAS_PK" PRIMARY KEY ("ID_TAREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."TAREAS" MODIFY ("ID_TIPO_TAREA" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."TAREAS" MODIFY ("ID_TAREA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MASSENDING
--------------------------------------------------------

  ALTER TABLE "APIINST"."MASSENDING" ADD CONSTRAINT "MASSENDING_PK" PRIMARY KEY ("IDMASSENDING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."MASSENDING" MODIFY ("IDMASSENDING" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MASSENDING" MODIFY ("PK_MLOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEVICE
--------------------------------------------------------

  ALTER TABLE "APIINST"."DEVICE" ADD CONSTRAINT "DEVICE_PK" PRIMARY KEY ("DEVICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("FIRMWARETYPE" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("FIRMWARETAGS" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("FIRMWAREFINGERPRINT" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("RESOLUTION" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("DPI" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("DEVICEMODELIDENTIFIER" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("DEVICEMODELBOOT" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("DEVICEMODEL" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("DEVICEID" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("DEVICEGUID" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("DEVICEBRAND" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("ANDROIDVER" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("ANDROIDBOOTLOADER" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("ANDROIDBOARDNAME" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."DEVICE" MODIFY ("ADID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_TAREA
--------------------------------------------------------

  ALTER TABLE "APIINST"."TIPO_TAREA" ADD CONSTRAINT "TIPO_TAREA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."TIPO_TAREA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURIFICADOR
--------------------------------------------------------

  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("ID_TAREA" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PURIFICADOR" ADD CONSTRAINT "PURIFICADOR_PK" PRIMARY KEY ("ID_PURIFICADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("PK_MLOGIN" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."PURIFICADOR" MODIFY ("ID_PURIFICADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MFOLLOWER
--------------------------------------------------------

  ALTER TABLE "APIINST"."MFOLLOWER" ADD CONSTRAINT "MFOLLOWER_PK" PRIMARY KEY ("PK_OTHERUSER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."MFOLLOWER" MODIFY ("PK_MLOGIN" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MFOLLOWER" MODIFY ("OTHERUSER" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MFOLLOWER" MODIFY ("PK_OTHERUSER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BITACORA
--------------------------------------------------------

  ALTER TABLE "APIINST"."BITACORA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."BITACORA" ADD CONSTRAINT "BITACORA_PK" PRIMARY KEY ("ID_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."BITACORA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."BITACORA" MODIFY ("ID_TAREA" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."BITACORA" MODIFY ("PK_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."BITACORA" MODIFY ("ID_LOG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MLIKEMANYPOST
--------------------------------------------------------

  ALTER TABLE "APIINST"."MLIKEMANYPOST" MODIFY ("PK_MLOGIN" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MLIKEMANYPOST" ADD CONSTRAINT "MLIKEMANYPOST_PK" PRIMARY KEY ("ID_MLIKE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."MLIKEMANYPOST" MODIFY ("CANTLIKE" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MLIKEMANYPOST" MODIFY ("ID_MLIKE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table METHODLIKE
--------------------------------------------------------

  ALTER TABLE "APIINST"."METHODLIKE" MODIFY ("ID_TAREA" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."METHODLIKE" ADD CONSTRAINT "METHODLIKE_PK" PRIMARY KEY ("ID_METHODLIKE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."METHODLIKE" MODIFY ("MLIKE" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."METHODLIKE" MODIFY ("VELOCIDAD" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."METHODLIKE" MODIFY ("ID_METHODLIKE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORTES
--------------------------------------------------------

  ALTER TABLE "APIINST"."REPORTES" ADD CONSTRAINT "REPORTES_PK" PRIMARY KEY ("ID_REPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."REPORTES" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."REPORTES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."REPORTES" MODIFY ("ID_REPORTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANDROID_VERSION
--------------------------------------------------------

  ALTER TABLE "APIINST"."ANDROID_VERSION" ADD CONSTRAINT "ANDROID_VERSION_PK" PRIMARY KEY ("IDANDROIDVERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APIINST"."ANDROID_VERSION" MODIFY ("IDANDROIDVERSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MLOGIN
--------------------------------------------------------

  ALTER TABLE "APIINST"."MLOGIN" MODIFY ("DEVICE" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MLOGIN" MODIFY ("PROXY" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MLOGIN" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MLOGIN" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "APIINST"."MLOGIN" ADD CONSTRAINT "MLOGIN_PK" PRIMARY KEY ("PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_APIINST"  ENABLE;
  ALTER TABLE "APIINST"."MLOGIN" MODIFY ("PK" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BITACORA
--------------------------------------------------------

  ALTER TABLE "APIINST"."BITACORA" ADD CONSTRAINT "ID_TAREA_FK" FOREIGN KEY ("ID_TAREA")
	  REFERENCES "APIINST"."TAREAS" ("ID_TAREA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "APIINST"."BITACORA" ADD CONSTRAINT "PK_LOGIN" FOREIGN KEY ("PK_LOGIN")
	  REFERENCES "APIINST"."MLOGIN" ("PK") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEVICE
--------------------------------------------------------

  ALTER TABLE "APIINST"."DEVICE" ADD CONSTRAINT "ANDROIDVERSION_FK1" FOREIGN KEY ("ANDROIDVER")
	  REFERENCES "APIINST"."ANDROID_VERSION" ("IDANDROIDVERSION") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MASSENDING
--------------------------------------------------------

  ALTER TABLE "APIINST"."MASSENDING" ADD CONSTRAINT "PK_MLOGIN" FOREIGN KEY ("PK_MLOGIN")
	  REFERENCES "APIINST"."MLOGIN" ("PK") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table METHODLIKE
--------------------------------------------------------

  ALTER TABLE "APIINST"."METHODLIKE" ADD CONSTRAINT "MLIKE_FK" FOREIGN KEY ("MLIKE")
	  REFERENCES "APIINST"."MLIKEMANYPOST" ("ID_MLIKE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "APIINST"."METHODLIKE" ADD CONSTRAINT "TAREA_FK" FOREIGN KEY ("ID_TAREA")
	  REFERENCES "APIINST"."TAREAS" ("ID_TAREA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MFOLLOWER
--------------------------------------------------------

  ALTER TABLE "APIINST"."MFOLLOWER" ADD CONSTRAINT "FK_MLOGIN" FOREIGN KEY ("PK_MLOGIN")
	  REFERENCES "APIINST"."MLOGIN" ("PK") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MLIKEMANYPOST
--------------------------------------------------------

  ALTER TABLE "APIINST"."MLIKEMANYPOST" ADD CONSTRAINT "MLOGIN_FK" FOREIGN KEY ("PK_MLOGIN")
	  REFERENCES "APIINST"."MLOGIN" ("PK") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MLOGIN
--------------------------------------------------------

  ALTER TABLE "APIINST"."MLOGIN" ADD CONSTRAINT "DEVICE_FK" FOREIGN KEY ("DEVICE")
	  REFERENCES "APIINST"."DEVICE" ("DEVICEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "APIINST"."MLOGIN" ADD CONSTRAINT "PROXY_FK" FOREIGN KEY ("PROXY")
	  REFERENCES "APIINST"."PROXY" ("ID_PROXY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURIFICADOR
--------------------------------------------------------

  ALTER TABLE "APIINST"."PURIFICADOR" ADD CONSTRAINT "ID_TAREA_PURI_FK" FOREIGN KEY ("ID_TAREA")
	  REFERENCES "APIINST"."TAREAS" ("ID_TAREA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "APIINST"."PURIFICADOR" ADD CONSTRAINT "PURIFICADOR_LOGIN_FK" FOREIGN KEY ("PK_MLOGIN")
	  REFERENCES "APIINST"."MLOGIN" ("PK") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT_MESS
--------------------------------------------------------

  ALTER TABLE "APIINST"."REPORT_MESS" ADD CONSTRAINT "REPORT_MESS_LOGIN_FK" FOREIGN KEY ("PK_MLOGIN")
	  REFERENCES "APIINST"."MLOGIN" ("PK") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAREAS
--------------------------------------------------------

  ALTER TABLE "APIINST"."TAREAS" ADD CONSTRAINT "ID_TIPO_FK" FOREIGN KEY ("ID_TIPO_TAREA")
	  REFERENCES "APIINST"."TIPO_TAREA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "APIINST"."USUARIOS" ADD CONSTRAINT "METHODLIKE_FK" FOREIGN KEY ("METHODLIKE")
	  REFERENCES "APIINST"."METHODLIKE" ("ID_METHODLIKE") ON DELETE CASCADE ENABLE;
